from enum import Enum

from pydantic import BaseModel


class ErrorCode(str, Enum):
    EMPTY_INPUT = "EMPTY_INPUT"
    UNSUPPORTED_FILE_TYPE = "UNSUPPORTED_FILE_TYPE"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    INVALID_PDF = "INVALID_PDF"
    PDF_NO_TEXT = "PDF_NO_TEXT"
    UNSUPPORTED_ENCODING = "UNSUPPORTED_ENCODING"
    BPE_TRAINING_TEXT_EMPTY = "BPE_TRAINING_TEXT_EMPTY"
    BPE_TRAINING_TEXT_TOO_LONG = "BPE_TRAINING_TEXT_TOO_LONG"
    BPE_TARGET_VOCAB_SIZE_INVALID = "BPE_TARGET_VOCAB_SIZE_INVALID"
    BPE_MODEL_NOT_TRAINED = "BPE_MODEL_NOT_TRAINED"
    BPE_UNKNOWN_CHARACTER = "BPE_UNKNOWN_CHARACTER"


class ErrorResponse(BaseModel):
    error_code: ErrorCode
    message: str
